---
- name: Create auth log if it does not exist
  ansible.builtin.command: touch /var/log/auth.log
  args:
    creates: /var/log/auth.log

- name: Ensure fail2ban is installed
  ansible.builtin.apt:
    name: fail2ban
    state: latest
    update_cache: true
  notify:
    - Restart fail2ban

- name: Ensure fail2ban is configured
  ansible.builtin.template:
    src: "fail2ban/templates/{{ item }}.j2"
    dest: /etc/fail2ban/{{ item }}
  with_items:
    - jail.local
    - fail2ban.local
  notify:
    - Restart fail2ban

- name: Ensure fail2ban starts when machine is rebooted
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
