version: '3'
services:
  inf:
    container_name: infrastructure-local
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./:/src
    working_dir: /src
    env_file:
      - env.list
  ssh:
    image: "rastasheep/ubuntu-sshd:18.04"
    ports: ["22:22","8080:8080"]
