---
fail2ban_loglevel: INFO
fail2ban_bantime: 7200
fail2ban_maxretry: 3
fail2ban_destemail: root@localhost

fail2ban_services:
  - name: ssh
    port: ssh
    filter: sshd
    logpath: /var/log/auth.log