---
additional_storage: false
restart_ssh: false
fail2ban_enable: false
enable_aws_checks: false
service_mgr: sysvinit
node_exporter_enabled: false

project_root: /root/node
packages_path: /tmp
vault_config_key: ""

docker_tag: "1.66.4"
