mappings:
### Worker Queues Metrics
- match: "ae.epoch.aecore.queues.*.*.value"
  name: "aecore_queues_size"
  labels:
    name: "$1"
    status: "$2"

- match: "ae.epoch.aecore.queues.*.*.wait.mean"
  name: "aecore_queues_wait"
  labels:
    name: "$1"
    status: "$2"

### Sync Metrics
- match: "ae.epoch.aecore.sync.progress.value"
  name: "aecore_sync_progress"

### General Info Metrics
- match: "ae.epoch.aecore.blocks.key.info.value"
  name: "aecore_blocks_info"

### Execution Time Metrics
- match: "ae\\.epoch\\.aecore\\.blocks\\.(\\w+)\\.(\\w+)_execution_time\\.(\\w+)\\.mean"
  match_type: regex
  name: "aecore_${1}_blocks_execution_time"
  labels:
    type: "$2"
    status: "$3"

### Peers Metrics
- match: "ae\\.epoch\\.aecore\\.peers\\.(unverified|verified|blocked|errored)\\.value"
  match_type: regex
  name: "aecore_peers_bucket"
  labels:
    bucket: "$1"

- match: "ae\\.epoch\\.aecore\\.peers\\.(inbound|outbound)\\.value"
  match_type: regex
  name: "aecore_peers_connection"
  labels:
    direction: "$1"

- match: "ae.epoch.aecore.peers.ping.*.value"
  name: "aecore_peers_ping"
  labels:
    status: "$1"

### TX Pool Metrics
- match: "ae.epoch.aecore.tx_pool.pending_txs"
  name: "aecore_txpool_size"

- match: "ae.epoch.aecore.tx_pool.gced.value"
  name: "aecore_txpool_gc_total"
  labels:
    bucket: "memory"

- match: "ae.epoch.aecore.tx_pool.origin_gced.value"
  name: "aecore_txpool_gc_total"
  labels:
    bucket: "origin_cache"

- match: "ae.epoch.aecore.tx_pool.push.value"
  name: "aecore_txpool_push_total"
  labels:
    status: "success"

- match: "ae.epoch.aecore.tx_pool.push.*.value"
  name: "aecore_txpool_push_total"
  labels:
    status: "$1"

### Mining Metrics
- match: "ae.epoch.aecore.mining.retries.value"
  name: "aecore_mining_retries_total"

- match: "ae.epoch.aecore.mining.blocks_mined.value"
  name: "aecore_mining_blocks_total"

- match: "ae.epoch.aecore.mining.interval.mean"
  name: "aecore_mining_blocks_interval"

### Chain Metrics
- match: "ae.epoch.aecore.chain.total_difficulty"
  name: "aecore_chain_total_difficulty"

- match: "ae.epoch.aecore.chain.height.value"
  name: "aecore_chain_height"

- match: "ae.epoch.aecore.chain.top_change.interval.mean"
  name: "aecore_chain_top_interval"

### Aemon core monitoring app
- match: "ae.epoch.aemon.block.gas.per_tx.micro.mean"
  name: "aecore_aemon_transaction_gas"

- match: "ae.epoch.aemon.block.gas.total.micro.mean"
  name: "aecore_aemon_microblock_gas"

- match: "ae.epoch.aemon.block.propagation_time.key.mean"
  name: "aecore_aemon_keyblock_propagation_ms"
  help: "Time until key-blocks reached this node in milliseconds"

- match: "ae.epoch.aemon.block.propagation_time.micro.mean"
  name: "aecore_aemon_microblock_propagation_ms"
  help: "Time until micro-blocks reached this node in milliseconds"

- match: "ae.epoch.aemon.block.size.per_tx.micro.mean"
  name: "aecore_aemon_transaction_size_bytes"

- match: "ae.epoch.aemon.block.time_since_prev.key.mean"
  name: "aecore_aemon_keyblock_interval_ms"
  help: "Time between key-blocks in milliseconds"

- match: "ae.epoch.aemon.block.time_since_prev.micro.mean"
  name: "aecore_aemon_microblock_interval_ms"
  help: "Time between micro-blocks in milliseconds"

- match: "ae.epoch.aemon.block.tx.total.micro.mean"
  name: "aecore_aemon_microblock_transactions"
  help: "Number of transactions in a microblock"

- match: "ae.epoch.aemon.chain.top.difficulty.value"
  name: "aecore_aemon_chain_current_difficulty"

- match: "ae.epoch.aemon.confirmation.delay.mean"
  name: "aecore_aemon_confirmation_delay"
  help: "Number of keyblocks bofore test/monitoring TX gets included in a generation"

- match: "ae.epoch.aemon.forks.micro.count.value"
  name: "aecore_aemon_microforks_total"
  help: "Count of observed micro-forks"

- match: "ae.epoch.aemon.forks.micro.height.mean"
  name: "aecore_aemon_microforks_height"
  help: "Height difference of observed micro-forks"

- match: "ae.epoch.aemon.gen_stats.microblocks.total.mean"
  name: "aecore_aemon_generation_microblocks"

- match: "ae.epoch.aemon.gen_stats.tx.total.mean"
  name: "aecore_aemon_generation_transactions"

- match: "ae.epoch.aemon.gen_stats.tx.monitoring.mean"
  name: "aecore_aemon_generation_mon_transactions"

- match: "ae.epoch.aemon.publisher.queue.size.mean"
  name: "aecore_aemon_publisher_queue_size"
  help: "Number of monitoring transactions posted but not wet on chain"

- match: "ae.epoch.aemon.publisher.queue.ttl_expired.mean"
  name: "aecore_aemon_publisher_queue_expired"
  help: "Number of expired monitoring transactions"

- match: "ae.epoch.aemon.publisher.post_tx.*"
  name: "aecore_aemon_publisher_transactions_total"
  help: "Number of monitoring transactions posted by their status"
  labels:
    status: "$1"

#TODO - piblisher balances

### Erlang System Metrics
- match: "ae.epoch.system.io.*.value"
  name: "erlang_system_io"
  labels:
    type: "$1"

- match: "ae.epoch.system.monitor.*.value"
  name: "erlang_system_monitor_${1}"

- match: "ae.epoch.system.procs.value"
  name: "erlang_system_processes"

- match: "ae.epoch.system.memory.*.value"
  name: "erlang_system_memory_allocated_bytes"
  labels:
    type: "$1"

- match: "ae.epoch.system.memory.total.value"
  action: drop
  name: "dropped"

- match: "ae.epoch.system.memory.system.value"
  name: "erlang_system_memory_system_bytes"

- match: "ae.epoch.system.memory.*.value"
  name: "erlang_system_memory_allocated_bytes"
  labels:
    type: "$1"

- match: "ae.epoch.system.memory.*.used.value"
  name: "erlang_system_memory_used_bytes"
  labels:
    type: "$1"

# drop all not explicitly mapped
- match: "."
  match_type: regex
  action: drop
  name: "dropped"
