Parameters:
    InstanceType:
        Type: String
        Description: Instance size
    AmiId:
        Type: String
        Description: AMI id
    EnvName:
        Type: String
        Description: Environment name
    ApiPort:
        Type: Number
        Description: Port number of epoch node API
        Default: 3013
    NodeCount:
        Type: Number
        Description: Number of epoch nodes
        Default: 2

Resources:

    ManagementSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
          GroupName:
              Fn::Sub:
                - "ae-${EnvName}-management"
                - { EnvName: !Ref EnvName}
          GroupDescription: Allow node management from internet (ICMP, SSH, API)
          SecurityGroupIngress:
          - FromPort: !Ref ApiPort
            ToPort: !Ref ApiPort
            CidrIp: 0.0.0.0/0
            IpProtocol: "tcp"
          - FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
            IpProtocol: "tcp"
          - FromPort: 8
            ToPort: -1
            IpProtocol: "icmp"
            CidrIp: 0.0.0.0/0

    EpochSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
        GroupName:
            Fn::Sub:
              - "ae-${EnvName}-nodes"
              - { EnvName: !Ref EnvName}
        GroupDescription: Full access between epoch nodes in their environment

    EpochSecurityGroupIngress:
      Type: 'AWS::EC2::SecurityGroupIngress'
      Properties:
        GroupName: !Ref EpochSecurityGroup
        FromPort: 0
        ToPort: 65535
        SourceSecurityGroupName: !Ref EpochSecurityGroup
        IpProtocol: "tcp"

    EpochServerLaunchConfiguration:
      Type: "AWS::AutoScaling::LaunchConfiguration"
      Properties:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        SecurityGroups:
        - !Ref EpochSecurityGroup
        - !Ref ManagementSecurityGroup

    EpochServerAutoScalingGroup:
      Type: "AWS::AutoScaling::AutoScalingGroup"
      Properties:
        AutoScalingGroupName:
          Fn::Sub:
            - "ae-${EnvName}-auto-scaling-group"
            - { envname: !Ref EnvName}
        LaunchConfigurationName: !Ref EpochServerLaunchConfiguration
        MinSize: !Ref NodeCount
        MaxSize: !Ref NodeCount
        Tags:
        - Key: Name
          Value:
            Fn::Sub:
              - "ae-${EnvName}-nodes"
              - { envname: !Ref EnvName}
          PropagateAtLaunch: 'true'

        - Key: role
          Value: epoch
          PropagateAtLaunch: 'true'

        - Key: env
          Value: !Ref EnvName
          PropagateAtLaunch: 'true'

        AvailabilityZones:
          Fn::GetAZs:
            Ref: "AWS::Region"

    EpochElasticIP:
      Type: "AWS::EC2::EIP"
