---
- name: Check if running on AWS instance
  ansible.builtin.uri:
    url: http://169.254.169.254/latest/meta-data
    timeout: 2
  register: aws_uri_check
  failed_when: false
  tags: [always]

- name: Set AWS check fact
  ansible.builtin.set_fact:
    is_aws: "{{ aws_uri_check.status == 200 }}"
  tags: [always]

- name: "Set /dev/nvme0n1 as additional storage device name"
  ansible.builtin.set_fact:
    additional_storage_dev: "/dev/nvme0n1"
  tags: [always]
  when:
    - additional_storage is defined
    - additional_storage | bool
    - additional_storage_mountpoint is defined
    - is_aws
    - ansible_devices.nvme0n1.partitions.keys() | length | int == 0

- name: "Set /dev/nvme1n1 as additional storage device name"
  ansible.builtin.set_fact:
    additional_storage_dev: "/dev/nvme1n1"
  tags: [always]
  when:
    - additional_storage is defined
    - additional_storage | bool
    - additional_storage_mountpoint is defined
    - is_aws
    - ansible_devices.nvme1n1.partitions.keys() | length | int == 0

- name: Wait for {{ additional_storage_dev ~ ' to become present' }}
  ansible.builtin.wait_for:
    path: "{{ additional_storage_dev }}"
    state: present
  when: additional_storage_dev is defined

- name: Create a xfs filesystem on {{ additional_storage_dev }}
  community.general.filesystem:
    fstype: xfs
    dev: "{{ additional_storage_dev }}"
  when: additional_storage_dev is defined

- name: Mount disk {{ additional_storage_mountpoint }}
  ansible.posix.mount:
    path: "{{ additional_storage_mountpoint }}"
    src: "{{ additional_storage_dev }}"
    fstype: xfs
    state: mounted
  when: additional_storage_dev is defined

- name: Make sure that node will be able to access storage
  ansible.builtin.file:
    path: "{{ additional_storage_mountpoint }}"
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    mode: '0755'
  when: additional_storage_dev is defined

- name: Make sure middleware storage directory exists
  ansible.builtin.file:
    path: "{{ additional_storage_mountpoint }}/aemdw"
    owner: "{{ aemdw_user }}"
    group: "{{ aemdw_user }}"
    state: directory
    mode: '0744'
  when: additional_storage_dev is defined
