---
- name: Check aeternity binary
  ansible.builtin.stat:
    path: "{{ project_root }}/bin/aeternity"
  register: ae_node
  tags: [daemon]
  listen:
    - "stop aeternity daemon"
    - "restart aeternity daemon"

- name: Ping aeternity node
  ansible.builtin.command: "{{ project_root }}/bin/aeternity ping"
  failed_when: false
  register: ping
  when: ae_node.stat.exists == True
  tags: [daemon]
  listen:
    - "stop aeternity daemon"
    - "restart aeternity daemon"

- name: Stop aeternity node
  ansible.builtin.command: "{{ project_root }}/bin/aeternity stop"
  when: ae_node.stat.exists == True and ping.stdout == "pong"
  tags: [daemon]
  listen:
    - "stop aeternity daemon"
    - "restart aeternity daemon"

- name: Start aeternity node
  ansible.builtin.command: "{{ project_root }}/bin/aeternity start"
  tags: [daemon]
  listen:
    - "start aeternity daemon"
    - "restart aeternity daemon"
