---
- name: Wait aeternity node API to boot
  wait_for:
    port: "{{ node_config.http.external.port }}"
    host: "{{ public_ipv4 }}"
    timeout: 180
  connection: local

- name: API health check
  uri:
    url: "{{ api_base_uri }}/blocks/top"
    timeout: 30
  connection: local

- name: Copy test files
  copy:
    directory_mode: true
    src: ../test/goss/local/
    dest: "{{ health_config_location }}"

- name: Copy health check script
  copy:
    src: ../scripts/health_check.sh
    dest: "{{ health_config_location }}"

- name:  Run health checks
  command: goss -g {{ health_config_location }}/health.yml validate
  register: output
  changed_when: "output.stdout is search('Failed: 0, Skipped: 0')"
