---
- name: Wait for system to become reachable
  wait_for_connection:
    timeout: 180

- name: Wait aeternity node API to boot
  wait_for:
    port: "{{ node_config.http.external.port }}"
    host: "127.0.0.1"
    timeout: 180
  tags: [health-check]

- name: Local Health check
  uri:
    url: "http://127.0.0.1:{{ node_config.http.external.port }}/v2/status"
    timeout: 40
    status_code: 200
  tags: [health-check]

- name: Goss Health check
  uri:
    url: "http://{{public_ipv4}}:8080/healthz"
    timeout: 10
    status_code: 200
  connection: local
  register: result
  until: result.status == 200
  retries: 10
  delay: 3
  when: goss_health_check is defined
  tags: [health-check]
