---
- name: Copy test files
  copy:
    directory_mode: true
    src: ../test/goss/local/
    dest: /tmp/

- name:  Test user existance
  command: goss -g /tmp/users.yml validate


- name: Wait aeternity node API to boot
  wait_for:
    port: "{{ node_config.http.external.port }}"
    host: "{{ public_ipv4 }}"
    timeout: 180
  connection: local

- name: API health check
  uri:
    url: "{{ api_base_uri }}/blocks/top"
    timeout: 30
  connection: local
