---
- name: Wait for system to become reachable
  wait_for_connection:
    timeout: 180

- name: Wait aeternity node API to boot
  wait_for:
    port: "{{ healthcheck_port }}"
    host: "127.0.0.1"
    timeout: 600
  tags: [health-check]

- name: Local Node Health check
  uri:
    url: "http://127.0.0.1:{{ healthcheck_port }}/v2/status"
    timeout: 1
    status_code: 200
  register: node_uri_output
  until: node_uri_output.status == 200
  retries: 6
  delay: 10
  tags: [health-check]

- name: External Node Health check
  uri:
    url: "http://{{ public_ipv4 }}:{{ healthcheck_port }}/v2/status"
    timeout: 5
    status_code: 200
  connection: local
  tags: [health-check]

- name: Local Middleware Health check
  uri:
    url: "http://127.0.0.1:{{ mdw_healthcheck_port }}/status"
    timeout: 1
    status_code: 200
  register: mdw_uri_output
  until: mdw_uri_output.status == 200
  retries: 6
  delay: 10
  when:
    - mdw_healthcheck_enable is defined
    - mdw_healthcheck_enable|bool
  tags: [health-check]

- name: External Middleware Health check
  uri:
    url: "http://{{ public_ipv4 }}:{{ mdw_healthcheck_port }}/status"
    timeout: 5
    status_code: 200
  when:
    - mdw_healthcheck_enable is defined
    - mdw_healthcheck_enable|bool
  connection: local
  tags: [health-check]

- name: Goss Health check
  uri:
    url: "http://{{ public_ipv4 }}:8080/healthz"
    timeout: 10
    status_code: 200
  connection: local
  register: result
  until: result.status == 200
  retries: 10
  delay: 3
  when: goss_health_check is defined
  tags: [health-check]
