---
- name: Wait epoch node API to boot
  wait_for:
    port: "{{ epoch_config.http.external.port }}"
    host: "{{ public_ipv4 }}"
    timeout: 30
  connection: local

- name: API health check
  uri:
    url: "{{ api_base_uri }}/blocks/top"
    timeout: 30
  connection: local
