---
- name: Wait aeternity node API to boot
  wait_for:
    port: "{{ node_config.http.external.port }}"
    host: "{{ public_ipv4 }}"
    timeout: 180
  connection: local
  tags: [health-check]

- name: Health check
  uri:
    url: "http://{{public_ipv4}}:8080/healthz"
    timeout: 10
    status_code: 200
  connection: local
  register: result
  until: result.status == 200
  retries: 10
  delay: 3
  tags: [health-check]
