---
- name: Wait aeternity node API to boot
  wait_for:
    port: "{{ node_config.http.external.port }}"
    host: "{{ public_ipv4 }}"
    timeout: 180
  connection: local
  tags: [health-check]

- name: Health check
  uri:
    url: "http://{{public_ipv4}}:8080/healthz"
    timeout: 10
  connection: local
  tags: [health-check]
