- name: Download libsodium
  ansible.builtin.unarchive:
    src: https://github.com/jedisct1/libsodium/releases/download/{{ libsodium_version }}/libsodium-{{ libsodium_version }}.tar.gz
    dest: /usr/local/src/
    remote_src: true
  tags:
    - libsodium

- name: Install libsodium
  ansible.builtin.command: "{{ item }}"
  with_items:
    - ./configure
    - make
    - make install
  args:
    chdir: "/usr/local/src/libsodium-{{ libsodium_version }}"
    creates: "/usr/local/lib/libsodium.so.{{ libsodium_module_version }}"
  tags:
    - libsodium
  # ldconfig should run in separate process, thus cannot be added in the above command list
  notify: run ldconfig
