- name: Install Ubuntu 22.04 dependency packages
  apt:
    pkg:
      - libsodium23
      - libtinfo5
      - libssl1.1

# remove once Vault is updated to support more modern algos
- name: Enable legacy CA algos in sshd config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^CASignatureAlgorithms \\^ssh-rsa'
    line: 'CASignatureAlgorithms ^ssh-rsa'
  when: vault_addr is defined
  tags:
    - ssh-keys
    - developer-ssh-keys
  notify: restart ssh
