- name: Install Ubuntu 22.04 dependency packages
  apt:
    pkg:
      - libsodium23
      - libtinfo5

# Remove once new AMIs are build
- name: Remove old libssl deb package
  apt:
    deb: "http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.21_amd64.deb"
    state: absent

# Make sure it's not in the update cycle still
- name: Install Ubuntu 22.04 dependency debs
  apt:
    deb: "http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb"

# remove once Vault is updated to support more modern algos
- name: Enable legacy CA algos in sshd config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^CASignatureAlgorithms \\^ssh-rsa'
    line: 'CASignatureAlgorithms ^ssh-rsa'
  when: vault_addr is defined
  tags:
    - ssh-keys
    - developer-ssh-keys
  notify: restart ssh
