---
{% if configure_peers|default(true) and hosts_group is defined %}
peers:
{% for host in groups[hosts_group] | difference([inventory_hostname]) %}
{% set public_ip = hostvars[host]['ansible_ssh_host']|default(hostvars[host]['ansible_host'])|default(host) -%}
{% if hostvars[host]['ansible_local']['aeternity']['peer_key'] %}
    - "aenode://{{ hostvars[host]['ansible_local']['aeternity']['peer_key'] }}@{{ public_ip }}:{{ node_config.sync.port }}"
{% else %}
    - "aenode://pp_nokeyfoundpeerwillbeignored@{{ public_ip }}:{{ node_config.sync.port }}"
{% endif %}
{% endfor %}
{% endif %}

{% if node_config is defined and node_config|length > 0 -%}
{{ node_config | to_nice_yaml }}
{% endif %}
