---
{% if configure_peers|default(true) and hosts_group is defined %}
peers:
{% for host in groups[hosts_group] | difference([inventory_hostname]) %}
{% set public_ip = hostvars[host]['ansible_ssh_host']|default(hostvars[host]['ansible_host'])|default(host) -%}
{% if hostvars[host]['ansible_local']['epoch']['peer_key'] %}
    - "aenode://{{ hostvars[host]['ansible_local']['epoch']['peer_key'] }}@{{ public_ip }}:{{ epoch_config.sync.port }}"
{% else %}
    - "aenode://pp$nokeyfoundpeerwillbeignored@{{ public_ip }}:{{ epoch_config.sync.port }}"
{% endif %}
{% endfor %}
{% endif %}

{% if epoch_config is defined and epoch_config|length > 0 -%}
{{ epoch_config | to_nice_yaml }}
{% endif %}
