api_base_uri: http://{{ public_ipv4 }}:{{ node_config.http.external.port }}/v2
configure_peers: false
seed_peers: []

node_config:
  sync:
    port: 3015
    max_gossip: 100

  http:
    external:
      port: 3013
    internal:
      port: 3113

  keys:
    dir: keys
    peer_password: secret

  chain:
    persist: true
    db_path: "./db{{ db_version|mandatory }}"

  mining:
    autostart: false

  logging:
    level: warning

  metrics:
      # StatsD server and port
      host: 127.0.0.1
      port: 8125

  fork_management:
    network_id: "ae_mainnet"
