datadog_enabled: yes
seed_peers: []
additional_storage: true
additional_storage_mountpoint: /data

node_config:
  http:
    external:
      port: 3013
    internal:
      port: 3113
      listen_address: 0.0.0.0
      debug_endpoints: true
    cache:
      enabled: true

  websocket:
    channel:
      port: 3014
      listen_address: 0.0.0.0

  keys:
    dir: keys
    peer_password: secret

  chain:
    persist: true
    db_path: "/data/db{{ db_version|mandatory }}"
    protocol_beneficiaries: ["ak_2A3PZPfMC2X7ZVy4qGXz2xh2Lbh79Q4UvZ5fdH7QVFocEgcKzU:109"]

  logging:
    level: debug

  mining:
    autostart: false

  metrics:
    # StatsD server and port
    host: 127.0.0.1
    port: 8125

  fork_management:
    network_id: ae_uat
