public_ipv4: "{{ ansible_ec2_public_ipv4|default(ansible_ssh_host)|default(ansible_host)|default(inventory_hostname) }}"
datadog_enabled: yes
seed_peers: []
additional_storage: true
additional_storage_mountpoint: /data

node_config:
  sync:
    port: 3015
    max_gossip: 100

  http:
    external:
      port: 3013
    internal:
      port: 3113
      listen_address: 0.0.0.0
      debug_endpoints: true

  keys:
    dir: keys
    peer_password: secret

  chain:
    persist: true
    db_path: "/data/db{{ db_version|mandatory }}"

  mining:
    autostart: false

  logging:
    level: warning

  metrics:
      # StatsD server and port
      host: 127.0.0.1
      port: 8125

  fork_management:
    network_id: "ae_mainnet"
