api_base_uri: http://{{ public_ipv4 }}:{{ node_config.http.external.port }}/v2
configure_peers: false
seed_peers: []
local_health_check: false

node_config:
  sync:
    port: 3015

  http:
    external:
      port: 3013
    internal:
      port: 3113

  keys:
    dir: keys
    peer_password: secret

  chain:
    persist: true
    db_path: "./db{{ db_version|mandatory }}"

  logging:
    level: debug
