public_ipv4: "{{ ansible_ec2_public_ipv4|default(ansible_ssh_host)|default(ansible_host)|default(inventory_hostname) }}"
datadog_enabled: yes
api_base_uri: http://{{ public_ipv4 }}:{{ node_config.http.external.port }}/v2
configure_peers: true
seed_peers: []

node_config:
  sync:
    port: 3015

  http:
    external:
      port: 3013
    internal:
      port: 3113

  keys:
    dir: keys
    peer_password: secret

  chain:
    persist: true
    db_path: "./db{{ db_version|mandatory }}"

  mining:
    autostart: true
    beneficiary: "ak_2VoAhMd7tVJrDYM5vPJwFRjueZyirDJumVJNeBWL9j1eNTHsRx"

  logging:
    level: debug

  fork_management:
    network_id: "ae_dev2"
