public_ipv4: "{{ ansible_ec2_public_ipv4|default(ansible_ssh_host)|default(ansible_host)|default(inventory_hostname) }}"
datadog_enabled: yes
additional_storage: true
additional_storage_mountpoint: /data
seed_peers: []

node_config:
  sync:
    port: 3015

  http:
    external:
      port: 3013
    internal:
      port: 3113

  keys:
    dir: keys
    peer_password: secret

  chain:
    persist: true
    db_path: "/data/db{{ db_version|mandatory }}"

  mining:
    autostart: true
    beneficiary: "ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688"
    cuckoo:
      edge_bits: 29
      miners:
        - executable: mean29-avx2
          extra_args: "-t 1"

  logging:
    level: debug

  metrics:
      # StatsD server and port
      host: 127.0.0.1
      port: 8125

  fork_management:
    network_id: "ae_uat"
