public_ipv4: "{{ ansible_ec2_public_ipv4|default(ansible_ssh_host)|default(ansible_host)|default(inventory_hostname) }}"
datadog_enabled: yes
api_base_uri: http://{{ public_ipv4 }}:{{ node_config.http.external.port }}/v2
monitoring_vault_path: "{{ 'secret/aenode/monitor/main/' + ansible_ec2_placement_region|default('global') + '/publisher' }}"
monitoring_pubkey: "{{ lookup('hashi_vault', 'secret=' + monitoring_vault_path + ':pubkey') }}"
monitoring_privkey: "{{ lookup('hashi_vault', 'secret=' + monitoring_vault_path + ':privkey') }}"
additional_storage: true
additional_storage_mountpoint: /data

node_config:
  sync:
    port: 3015

  http:
    external:
      port: 3013
    internal:
      port: 3113

  keys:
    dir: keys
    peer_password: secret

  chain:
    persist: true
    db_path: "/data/db{{ db_version|mandatory }}"

  logging:
    level: warning

  metrics:
      # StatsD server and port
      host: 127.0.0.1
      port: 8125

  fork_management:
    network_id: "ae_mainnet"

  monitoring:
    active: true
    publisher:
      autostart: true
      pubkey: "{{ monitoring_pubkey }}"
      privkey: "{{ monitoring_privkey }}"
      amount: 20000
      interval: 10000
      ttl: 10
