public_ipv4: "{{ ansible_ec2_public_ipv4|default(ansible_ssh_host)|default(ansible_host)|default(inventory_hostname) }}"
datadog_enabled: yes
api_base_uri: http://{{ public_ipv4 }}:{{ node_config.http.external.port }}/v2
seed_peers: [18.130.100.58]
configure_peers: false

node_config:
  peers:
    - aenode://pp_viEW93PwdaTgNKiorj4qygpLzUi8qoAmYLiPaUYCMkKzqNng5@18.130.100.58:3015
  sync:
    port: 3015

  http:
    external:
      port: 3013
    internal:
      port: 3113

  keys:
    dir: keys
    peer_password: secret

  chain:
    persist: true
    db_path: "./db{{ db_version|mandatory }}"
    hard_forks:
      "1": 0
      "2": 1
      "3": 2

  mining:
    autostart: true
    beneficiary: "ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688"
    cuckoo:
      edge_bits: 29
      miners:
        - executable: mean29-avx2
          extra_args: "-t 1"

  logging:
    level: warning

  metrics:
      # StatsD server and port
      host: 127.0.0.1
      port: 8125

  fork_management:
    network_id: "ae_next"
