public_ipv4: "{{ ansible_ec2_public_ipv4|default(ansible_ssh_host)|default(ansible_host)|default(inventory_hostname) }}"
datadog_enabled: yes
seed_peers: [18.130.100.58]

node_config:
  peers:
    - aenode://pp_viEW93PwdaTgNKiorj4qygpLzUi8qoAmYLiPaUYCMkKzqNng5@18.130.100.58:3015
  sync:
    port: 3015

  http:
    external:
      port: 3013
    internal:
      port: 3113
      listen_address: 0.0.0.0
      debug_endpoints: true

  keys:
    dir: keys
    peer_password: secret

  chain:
    persist: false
    db_path: "./db{{ db_version|mandatory }}"
    protocol_beneficiaries_enabled: true
    protocol_beneficiaries: ["ak_2A3PZPfMC2X7ZVy4qGXz2xh2Lbh79Q4UvZ5fdH7QVFocEgcKzU:109"]
    hard_forks:
      "1": 0
      "2": 1
      "3": 2
      "4": 3

  mining:
    autostart: true
    beneficiary: "ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688"
    expected_mine_rate: 30000
    cuckoo:
      edge_bits: 15
      miners:
        - executable: mean15-generic
          extra_args: "-t 1"

  logging:
    level: warning

  metrics:
      # StatsD server and port
      host: 127.0.0.1
      port: 8125

  fork_management:
    network_id: "ae_next"
