public_ipv4: "{{ ansible_ec2_public_ipv4|default(ansible_ssh_host)|default(ansible_host)|default(inventory_hostname) }}"
datadog_enabled: no
api_base_uri: http://{{ public_ipv4 }}:{{ node_config.http.external.port }}/v2
package: https://s3.eu-central-1.amazonaws.com/aeternity-node-builds/aeternity-latest-ubuntu-x86_64.tar.gz
configure_peers: true
seed_peers: []
db_version: 1
additional_storage: true
additional_storage_mountpoint: /data

node_config:
  sync:
    port: 3015

  http:
    external:
      port: 3013
    internal:
      port: 3113
      listen_address: 0.0.0.0
      debug_endpoints: true

  websocket:
    channel:
      port: 3014
      listen_address: 0.0.0.0

  keys:
    dir: keys
    peer_password: secret

  chain:
    persist: true
    db_path: "/data/db1"

  mining:
    autostart: false

  logging:
    level: debug

  metrics:
      # StatsD server and port
      host: 127.0.0.1
      port: 8125

  fork_management:
    network_id: "ae_test"
