datadog_enabled: yes
additional_storage: true
additional_storage_mountpoint: /data
seed_peers:
  - "52.10.46.160"
  - "18.195.109.60"
  - "13.250.162.250"
  - "13.53.161.215"

node_config:
  sync:
    port: 3015

  http:
    external:
      port: 3013
    internal:
      port: 3113

  keys:
    dir: keys
    peer_password: secret

  chain:
    persist: true
    db_path: "/data/db{{ db_version|mandatory }}"

  mining:
    autostart: true
    beneficiary: "ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688"
    cuckoo:
      edge_bits: 29
      miners:
        - executable: mean29-avx2
          extra_args: "-t 1"

  logging:
    level: warning

  metrics:
      # StatsD server and port
      host: 127.0.0.1
      port: 8125

  fork_management:
    network_id: "ae_uat"
