heat_template_version: 2015-10-15
description: Aeternity environment stack

parameters:
    env_name:
        type: string
        label: Environment name
    meta_groups:
        type: string
        label: Comma separataed list of metadata groups
        description: Groups used do manage ansible dynamic inventory
        default: "epoch"
    node_count:
        type: number
        label: Nodes Count
        description: Number of epoch nodes
        default: 2
        constraints:
          - range: { min: 0 }
            description: Only positive node count is accepted. Allow 0 for edge cases e.g. only static nodes.
    node_flavor:
        type: string
        label: Node Instance Type
        description: Type of instance (flavor) to deploy for the epoch node
        default: c1.medium
        constraints:
          - custom_constraint: nova.flavor
    key_name:
        type: string
        label: Key Name
        description: SSH key to be used for all instances
        default: "CircleCI Master"
        constraints:
          - custom_constraint: nova.keypair
    image_name:
        type: string
        label: Image Name
        description: Image name to create node servers
        default: "Ubuntu 16.04"
    external_api_port:
        type: number
        label: External (public) API port number
        description: Port number of epoch node external (public) API
        default: 3013
    external_sync_port:
        type: number
        label: Sync port number
        description: Port number of epoch node sync port
        default: 3015
    internal_ports:
        type: comma_delimited_list
        label: Internal port numbers
        description: Internal port numbers (WS, API) used to grant access to internal_access_prefixes
        default: "3113,3114"
    internal_access_prefixes:
        type: comma_delimited_list
        label: Internal access IP addresses
        description: IP addresses to allow access to internal_ports
        default: ""
    static_node_count:
        type: number
        label: Static (IP) Nodes Count
        description: Number of epoch nodes with floating (static) IP addresses
        default: 0
        constraints:
          - range: { min: 0, max: 1 }
            description: Either one or zero nodes. On/off switch.
    subnet_cidr:
      type: string
      label: Local network subnet CIDR
      description: Local network to connect all hosts attached to a router
      constraints:
        - custom_constraint: net_cidr
    ext_net_id:
      type: string
      label: External network ID
      description: ID of the external network to which the private network should be uplinked.
      default: ext-net
      constraints:
        - custom_constraint: nova.network

resources:
  management_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Allow node management from internet (ICMP, SSH, API)
      name:
        str_replace:
          template: ae-%env_name%-management
          params:
            "%env_name%": { get_param: env_name }
      rules:
        - direction: ingress
          remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: { get_param: external_api_port }
          port_range_max: { get_param: external_api_port }
        - direction: ingress
          remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: { get_param: external_sync_port }
          port_range_max: { get_param: external_sync_port }
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, protocol: tcp, port_range_min: 22, port_range_max: 22}
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, protocol: icmp }
        - { direction: egress, remote_ip_prefix: 0.0.0.0/0, protocol: udp, port_range_min: 123, port_range_max: 123}

  epoch_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Full access between epoch nodes in their environment
      name:
        str_replace:
          template: ae-%env_name%-nodes
          params:
            "%env_name%": { get_param: env_name }
      rules:
        # Allow all outgoing connections to Internet
        - { direction: egress, remote_ip_prefix: 0.0.0.0/0}
        # All all incoming connection from the same security group
        - { direction: ingress, remote_mode: remote_group_id }

  internal_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Allow access to internal ports
      name:
        str_replace:
          template: ae-%env_name%-internal
          params:
            "%env_name%": { get_param: env_name }
      rules:
        repeat:
          for_each:
            <%port%>: { get_param: internal_ports }
            <%prefix%>: { get_param: internal_access_prefixes }
          template:
            direction: ingress
            protocol: tcp
            remote_ip_prefix: <%prefix%>
            port_range_min: <%port%>
            port_range_max: <%port%>

  localnet:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name:
        str_replace:
          template: ae-%env_name%-net
          params:
            "%env_name%": { get_param: env_name }

  subnet:
    type: OS::Neutron::Subnet
    properties:
      name:
        str_replace:
          template: ae-%env_name%-subnet
          params:
            "%env_name%": { get_param: env_name }
      cidr: { get_param: subnet_cidr }
      enable_dhcp: true
      dns_nameservers: ["1.1.1.1", "1.0.0.1"]
      network_id: { get_resource: localnet }

  router:
    type: OS::Neutron::Router
    properties:
      admin_state_up: true
      name:
        str_replace:
          template: ae-%env_name%-router
          params:
            "%env_name%": { get_param: env_name }
      external_gateway_info: { "network": { get_param: ext_net_id }}

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: subnet }

  instance_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: localnet }
      security_groups:
        - {get_resource: management_security_group}
        - {get_resource: epoch_security_group}

  # Kind of hack because the OS provider does not support conditions because of OLD versions
  # Support is added in https://docs.openstack.org/heat/latest/template_guide/hot_spec.html#newton
  static_epoch_servers:
      type: OS::Heat::ResourceGroup
      properties:
          count: { get_param: static_node_count }
          resource_def:
              type: OS::Nova::Server
              properties:
                name:
                    str_replace:
                        template: ae-%env_name%-epoch-st-n%index%
                        params:
                          "%env_name%": { get_param: env_name }
                image: { get_param: image_name }
                flavor: { get_param: node_flavor }
                key_name: { get_param: key_name }
                metadata:
                  groups: { get_param: meta_groups }
                networks:
                  - port: { get_resource: instance_port }

  epoch_servers:
      type: OS::Heat::ResourceGroup
      properties:
          count: { get_param: node_count }
          resource_def:
              type: OS::Nova::Server
              properties:
                name:
                    str_replace:
                        template: ae-%env_name%-epoch-n%index%
                        params:
                          "%env_name%": { get_param: env_name }
                image: { get_param: image_name }
                flavor: { get_param: node_flavor }
                key_name: { get_param: key_name }
                metadata:
                  groups: { get_param: meta_groups }
                networks:
                  - network: ext-net
                security_groups:
                  - {get_resource: management_security_group}
                  - {get_resource: epoch_security_group}
                  - {get_resource: internal_security_group}
