---
- name: Provision node servers
  hosts: all
  remote_user: master
  become: true

  vars:
    bootstrap_version: master

  tasks:
    - name: Clone infrastructure repo
      ansible.builtin.git:
        repo: https://github.com/aeternity/infrastructure.git
        dest: /infrastructure
        version: "{{ bootstrap_version }}"
        depth: 1
        force: true

    - name: Run bootstrap.sh
      ansible.builtin.shell: |
        /infrastructure/scripts/bootstrap.sh >> /tmp/provision.log 2>&1
      async: 600
      poll: 15
      changed_when: false
