---
- name: Provision node servers
  hosts: all
  remote_user: master
  become: yes

  vars:
    var_bootstrap_version: "{{ bootstrap_version | default('master, true) }}"
    vault_role: ae-node
    var_package: "{{ package | default('http://s3.eu-central-1.amazonaws.com/aeternity-node-releases/aeternity-latest-ubuntu-x86_64.tar.gz', true) }}"

  tasks:
    - name: Clone infrastructure repo
      git:
        repo:  https://github.com/aeternity/infrastructure.git
        dest: /infrastructure
        version: "{{ var_bootstrap_version }}"
        depth: 1
        force: yes

    - name: Run bootstrap.sh
      shell: |
        /infrastructure/scripts/bootstrap.sh \
         --vault_addr={{ vault_addr }} \
         --vault_role={{ vault_role }} \
         --env={{ env }} \
         --aeternity_package={{ var_package }} \
         >> /tmp/provision.log 2>&1
      async: 600
      poll: 15
      changed_when: False
