---
- name: Manage aeternity nodes
  hosts: all
  remote_user: master
  become: yes

  vars:
    aeternity_bin: "{{ ansible_env.HOME }}/node/bin/aeternity"
    aeternity_action: "{{ cmd | default('ping') }}"
    node_running: false

  tasks:
    - name: "Load a variable files for environment: {{ env }}"
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/aeternity/{{ env }}.yml"

    - name: Check if running on AWS instance
      uri:
        url: http://169.254.169.254/latest/meta-data
        timeout: 2
      register: aws_uri_check
      failed_when: False
      tags: [always]

    - name: Set AWS check fact
      set_fact:
        is_aws: "{{ aws_uri_check.status == 200 }}"
      tags: [always]

    - name: Create a xfs filesystem on /dev/nvme1n1
      filesystem:
        fstype: xfs
        dev: /dev/nvme1n1
      when: additional_storage is defined and additional_storage and is_aws

    - name: Mount disk {{ additional_storage_mountpoint }}
      mount:
        path: "{{ additional_storage_mountpoint }}"
        src: /dev/nvme1n1
        fstype: xfs
        state: mounted
      when: additional_storage is defined and additional_storage ans is_aws
