---
- name: Deploy aeternity middleware
  hosts: all
  remote_user: master
  become_user: ubuntu
  become_flags: "-i"
  become: true
  serial: "{{ rolling_update | default('100%') }}"
  max_fail_percentage: 25

  vars:
    public_ipv4: "{{ ansible_ec2_public_ipv4|default(ansible_ssh_host) | default(ansible_host)|default(inventory_hostname) }}"
    aemdw_project_root: "/home/{{ ansible_user_id }}/aemdw"
    enable_aws_checks: true
    health_check: true
    healthcheck_port: 3013
    mdw_healthcheck_port: 4000
    aemdw_db_path: "{{ aemdw_project_root }}/db"
    aemdw_logs_path: "{{ aemdw_project_root }}/log"
    docker_repository: aeternity/ae_mdw
    docker_tag: "latest"
    accounts_path: /home/aeternity/node/data/aecore/.genesis/accounts_test.json
    contracts_path: /home/aeternity/node/data/aecore/.genesis/contacts_test.json
    # Label used for ENV file planting
    env: unknown

  tasks:
    - name: Check if running on AWS instance
      ansible.builtin.uri:
        url: http://169.254.169.254/latest/meta-data
        timeout: 2
      register: aws_uri_check
      failed_when: false
      when:
        - enable_aws_checks|bool
      tags: [always]

    - name: Set AWS check fact
      ansible.builtin.set_fact:
        is_aws: "{{ aws_uri_check.status == 200 }}"
      when:
        - enable_aws_checks|bool
      tags: [always]

    - name: Gather instance metadata facts
      amazon.aws.ec2_metadata_facts:
      tags: [always]
      when:
        - enable_aws_checks|bool
        - is_aws

    - name: Deploy
      block:
        - name: Make sure 'aemdw_project_root' exists
          ansible.builtin.file:
            path: "{{ aemdw_project_root }}"
            state: directory
            # allow group read for integration purposes  (e.g. logs)
            mode: '0750'

        - name: Make sure database directories exists
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
          loop:
            - "{{ aemdw_db_path }}"
            - "{{ aemdw_db_path }}/mnesia"
            - "{{ aemdw_db_path }}/mdw.db"
          tags: [config]

        - name: Make sure log directories exists
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
          loop:
            - "{{ aemdw_logs_path }}"
          tags: [config]

        - name: Update configuration files
          ansible.builtin.copy:
            content: "{{ lookup('hashi_vault', 'secret=secret2/data/aenode/config/{{ vault_config_key }}:{{ item.key }}') }}"
            dest: "{{ aemdw_project_root }}/{{ item.value }}"
            mode: '0600'
          loop: "{{ files | dict2items }}"
          when:
            - files is defined
            - vault_config_key is defined
            - vault_config_key != ""
          register: configs
          tags: [config]

        - name: Make sure aemdw container is running
          community.docker.docker_container:
            name: aemdw
            image: "{{ docker_repository }}:{{ docker_tag }}"
            pull: true
            ignore_image: false
            restart_policy: always
            restart: "{{ configs.changed }}"
            # currently it's not possible to run the container with other user than the default 1000/aeternity
            # user: "{{ ansible_user_id }}"
            user: 1000:1000
            env:
              # mount to default path?
              AETERNITY_CONFIG: "/home/aeternity/aeternity.yaml"
              # this is default? If the config file is mdw specific we don't need overwrite
              AE__CHAIN__DB_PATH: "/home/aeternity/node/data/mnesia"
              ENABLE_CONSOLE_LOG: "false"
              LOG_LEVEL: "error"
            volumes:
              - "{{ aemdw_db_path }}/mnesia:/home/aeternity/node/data/mnesia"
              - "{{ aemdw_db_path }}/mdw.db:/home/aeternity/node/data/mdw.db"
              - "{{ aemdw_logs_path }}:/home/aeternity/ae_mdw/log"
              - "{{ aemdw_project_root }}/accounts.json:{{ accounts_path }}"
              - "{{ aemdw_project_root }}/contracts.json:{{ contracts_path }}"
              - "{{ aemdw_project_root }}/aeternity.yaml:/home/aeternity/aeternity.yaml"
            ports:
              - "3013:3013"
              - "3113:3113"
              - "3014:3014"
              - "3015:3015"
              - "4000:4000"
              - "4001:4001"
            # TODO: added in ansible 2.8
            # healthcheck:
            #   test: ["CMD", "curl", "-f", "http://localhost:4000/status"]
            #   start_period: 30s
            #   interval: 30s
            #   timeout: 10s
            #   retries: 3
          tags: [container]

        - name: Wait middleware API to boot
          ansible.builtin.uri:
            url: "http://127.0.0.1:{{ mdw_healthcheck_port }}/status"
            timeout: 1
            status_code: 200
          register: uri_output
          until: uri_output.status == 200
          retries: 5
          delay: 5
          tags: [health-check]

        - name: Run node health checks
          ansible.builtin.include_tasks: tasks/health_check.yml
      rescue:
        - name: Fail the playbook
          ansible.builtin.fail:
            msg: "Failed deploy"
          when: true
