- name: Dump peer keys
  hosts: all
  remote_user: aeternity
  gather_facts: false

  vars:
    public_ipv4: "{{ ansible_ec2_public_ipv4|default(ansible_ssh_host)|default(ansible_host)|default(inventory_hostname) }}"

  tasks:
    - name: Get the base58c public key
      ansible.builtin.command: "/home/aeternity/node/bin/aeternity peer_key"
      register: public_key_base58c
      changed_when: public_key_base58c.stdout != ""
      tags: [public-key, vault-cmd]

    - name: Print base58c encoded public key
      ansible.builtin.debug:
        msg: "{{ public_key_base58c.stdout }}"
      tags: [public-key]

    - name: Print vault base58c encoded public key
      ansible.builtin.debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/aenode/peer_keys/{{ public_ipv4 }}/public:base58c') }}"
      tags: [public-key]

    - name: Get the base64 public key
      ansible.builtin.slurp:
        src: /home/aeternity/node/keys/peer_key.pub
      register: public_key_base64
      tags: [public-key, vault-cmd]

    - name: Print node base64 encoded public key
      ansible.builtin.debug:
        msg: "{{ public_key_base64['content'] }}"
      tags: [public-key]

    - name: Print node URL
      ansible.builtin.debug:
        msg: "aenode://{{ public_key_base58c.stdout }}@{{ public_ipv4 }}:3015"
      tags: [public-key, node-url]

    - name: Print vault command to create public key secret
      ansible.builtin.debug:
        msg: "vault write secret/aenode/peer_keys/{{ public_ipv4 }}/public base64={{ public_key_base64['content'] }} base58c={{ public_key_base58c.stdout }}"
      tags: [public-key, vault-cmd]

    - name: Print vault base64 encoded public key
      ansible.builtin.debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/aenode/peer_keys/{{ public_ipv4 }}/public:base64') }}"
      tags: [public-key]

    - name: Print check command
      ansible.builtin.debug:
        msg: "curl -fs -m 5 http://{{ public_ipv4 }}:3013/v3/peers/pubkey | grep -q '{{ public_key_base58c.stdout }}'"
      tags: [public-key, vault-cmd]

    - name: Get the private key
      ansible.builtin.slurp:
        src: /home/aeternity/node/keys/peer_key
      register: private_key
      tags: [private-key, vault-cmd]

    - name: Print node base64 encoded private key
      ansible.builtin.debug:
        msg: "{{ private_key['content'] }}"
      tags: [private-key]

    - name: Print vault command to create private key secret
      ansible.builtin.debug:
        msg: "vault write secret/aenode/peer_keys/{{ public_ipv4 }}/private base64={{ private_key['content'] }}"
      tags: [private-key, vault-cmd]

    - name: Print vault base64 encoded private key
      ansible.builtin.debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/aenode/peer_keys/{{ public_ipv4 }}/private:base64') }}"
      tags: [private-key]

    - name: Compare deployed keys to vault keys (base64)
      ansible.builtin.assert:
        that:
          - "{{ lookup('hashi_vault', 'secret=secret/aenode/peer_keys/{{ public_ipv4 }}/public:base58c') == public_key_base58c.stdout }}"
          - "{{ lookup('hashi_vault', 'secret=secret/aenode/peer_keys/{{ public_ipv4 }}/public:base64') == public_key_base64['content'] }}"
          - "{{ lookup('hashi_vault', 'secret=secret/aenode/peer_keys/{{ public_ipv4 }}/private:base64') == private_key['content'] }}"
