- name: Dump peer keys
  hosts: all
  remote_user: aeternity
  gather_facts: no

  tasks:
    - name: Get the base58c public key
      command: "/home/aeternity/node/bin/aeterity peer_key"
      register: public_key_base58c
      changed_when: public_key_base58c.stdout != ""

    - debug:
        msg: "Public key (base58c): {{ public_key_base58c.stdout }}"

    - name: Get the base64 public key
      slurp:
        src: /home/aeternity/node/keys/peer_key.pub
      register: public_key_base64

    - debug:
        msg: "Public key: {{ public_key_base64['content'] }}"

    - name: Get the private key
      slurp:
        src: /home/aeternity/node/keys/peer_key
      register: private_key

    - debug:
        msg: "Private key (base64): {{ private_key['content'] }}"

    - debug:
        msg: "aenode://{{ public_key_base58c.stdout }}@{{ public_ipv4 }}:3015"

    - debug:
        msg: "vault write secret/aenode/peer_keys/{{ public_ipv4 }}/public base64={{ public_key_base64['content'] }}"

    - debug:
        msg: "vault write secret/aenode/peer_keys/{{ public_ipv4 }}/private base64={{ private_key['content'] }}"
