- name: Dump peer keys
  hosts: all
  remote_user: aeternity
  gather_facts: no

  tasks:
    - name: Get the base58c public key
      command: "/home/aeternity/node/bin/aeternity peer_key"
      register: public_key_base58c
      changed_when: public_key_base58c.stdout != ""
      tags: [public-key]

    - name: Print base58c encoded public key
      debug:
        msg: "{{ public_key_base58c.stdout }}"
      tags: [public-key]

    - name: Get the base64 public key
      slurp:
        src: /home/aeternity/node/keys/peer_key.pub
      register: public_key_base64
      tags: [public-key, vault-cmd]

    - name: Print base64 encoded public key
      debug:
        msg: "{{ public_key_base64['content'] }}"
      tags: [public-key]

    - name: Print node URL
      debug:
        msg: "aenode://{{ public_key_base58c.stdout }}@{{ public_ipv4 }}:3015"
      tags: [public-key, node-url]

    - name: Print vault command to create public key secret
      debug:
        msg: "vault write secret/aenode/peer_keys/{{ public_ipv4 }}/public base64={{ public_key_base64['content'] }}"
      tags: [public-key, vault-cmd]

    - name: Get the private key
      slurp:
        src: /home/aeternity/node/keys/peer_key
      register: private_key
      tags: [private-key, vault-cmd]

    - name: Print base64 encoded private key
      debug:
        msg: "{{ private_key['content'] }}"
      tags: [private-key]

    - name: Print vault command to create private key secret
      debug:
        msg: "vault write secret/aenode/peer_keys/{{ public_ipv4 }}/private base64={{ private_key['content'] }}"
      tags: [private-key, vault-cmd]
