---
# Playbook used to increase XFS size to 100% of the additional storage (after EBS volume storage increase)

- name: Update FS size of EBS volume storage
  hosts: all
  remote_user: master
  become: yes

  tasks:
    - name: Check if running on AWS instance
      uri:
        url: http://169.254.169.254/latest/meta-data
        timeout: 2
      register: aws_uri_check
      failed_when: False
      tags: [always]

    - name: Set AWS check fact
      set_fact:
        is_aws: "{{ aws_uri_check.status == 200 }}"
      tags: [always]

    - name: "Load a variable files for environment: {{ env }}"
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - "vars/aeternity/{{ env }}.yml"
          skip: true

    - name: Grow XFS file system size
      command: "xfs_growfs -d {{ additional_storage_mountpoint }}"
      when:
        - is_aws
        - additional_storage is defined
        - additional_storage
        - additional_storage_mountpoint is defined
