---
# Playbook used to increase XFS size to 100% of the additional storage (after EBS volume storage increase)

- name: Update FS size of EBS volume storage
  hosts: all
  remote_user: master
  become: true

  tasks:
    - name: Check if running on AWS instance
      ansible.builtin.uri:
        url: http://169.254.169.254/latest/meta-data
        timeout: 2
      register: aws_uri_check
      failed_when: false
      tags: [always]

    - name: Set AWS check fact
      ansible.builtin.set_fact:
        is_aws: "{{ aws_uri_check.status == 200 }}"
      tags: [always]

    - name: Grow XFS file system size
      ansible.builtin.command: "xfs_growfs -d {{ additional_storage_mountpoint }}"
      when:
        - is_aws
        - additional_storage is defined
        - additional_storage
        - additional_storage_mountpoint is defined
