---
- name: Health check remote nodes
  hosts: all
  remote_user: aeternity
  gather_facts: false

  vars:
    env: unknown
    db_version: 0
    goss_health_check: true

  tasks:
    - name: "Load a variable files for environment: {{ env }}"
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/aeternity/{{ env }}.yml"

    - name: Run health checks
      include_tasks: tasks/health_check.yml
