---
- name: Health check remote nodes
  hosts: all
  remote_user: aeternity
  gather_facts: false

  vars:
    env: unknown
    db_version: 0
    goss_health_check: true
    public_ipv4: "{{ ansible_ec2_public_ipv4|default(ansible_ssh_host)|default(ansible_host)|default(inventory_hostname) }}"

  tasks:
    - name: "Load a variable files for environment: {{ env }}"
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/node_config.yml"
        - "vars/aeternity/{{ env }}.yml"

    - name: Run health checks
      include_tasks: tasks/health_check.yml
