---
- name: Health check remote nodes
  hosts: all
  remote_user: epoch

  vars:
    env: unknown
    db_version: 0

  tasks:
    - name: "Load a variable files for environment: {{ env }}"
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/epoch/{{ env }}.yml"
        - "vars/epoch/default.yml"

    - name: Run health checks
      include_tasks: tasks/health_check.yml
