---
- name: Manage aeternity nodes
  hosts: all
  remote_user: aeternity

  vars:
    aeternity_bin: "{{ ansible_env.HOME }}/node/bin/aeternity"
    aeternity_action: "{{ cmd | default('ping') }}"
    node_running: false

  tasks:
    - name: Fail on unsupported command
      fail:
        msg: "Invalid command. Supported commands are: ping, start, stop, restart, status"
      when:
        - aeternity_action != "ping"
        - aeternity_action != "start"
        - aeternity_action != "stop"
        - aeternity_action != "restart"
        - aeternity_action != "status"
      connection: local

    - name: Aeternity binary exists
      stat:
        path: "{{ aeternity_bin }}"
      register: ae_node
      changed_when: false
      failed_when: ae_node.stat.exists != True

    - name: Ping aeternity daemon
      command: "{{ aeternity_bin }} ping"
      register: ping
      failed_when: no
      changed_when: false
      when: ae_node.stat.exists == True

    - name: Register running aeternity daemon
      set_fact:
        node_running: true
      when: ping.stdout == "pong"

    - name: Fail if not running
      fail:
        msg: "Ping failed"
      when:
        - not node_running
        - aeternity_action == "ping"

    - name: Start aeternity deamon
      command: "{{ aeternity_bin }} start"
      when:
        - not node_running
        - aeternity_action == "start" or aeternity_action == "restart"

    - name: Stop aeternity deamon
      command: "{{ aeternity_bin }} stop"
      when:
        - node_running
        - aeternity_action == "stop"

    - name: Restart aeternity deamon
      command: "{{ aeternity_bin }} restart"
      when:
        - node_running
        - aeternity_action == "restart"

    - name: Dump node status
      block:
        - name: Get node status
          uri:
            url: "http://localhost:3013/v2/status"
          register: status
        - name: Print node status
          debug:
            var: status.json
      when:
        - node_running
        - aeternity_action == "status"

  post_tasks:
    - name: Prepare health checks
      include_tasks: tasks/health_check.yml
      when: aeternity_action != "stop"
