- hosts: all
  remote_user: epoch
  vars:
    epoch_exec: "{{ ansible_env.HOME }}/node/bin"
  tasks:
  - name: start
    command: "{{ epoch_exec }}/epoch start"
    tags: start
  - name: stop
    command: "{{ epoch_exec }}/epoch stop"
    tags: stop
  - name: restart
    command: "{{ epoch_exec }}/epoch restart"
    tags: restart
