---
- name: Manage epoch nodes
  hosts: all
  remote_user: epoch
  vars:
    project_root: "{{ ansible_env.HOME }}/node"
    stopped: false
  tasks:
  - name: Check if epoch binary exists
    stat:
      path: "{{ project_root }}/bin/epoch"
    register: epoch
    tags: stop, start, restart

  - name: Checking the epoch daemon state
    command: "{{ project_root }}/bin/epoch ping"
    failed_when: no
    register: ping
    when: epoch.stat.exists == True
    tags: stop, start, restart

  - name: Starting the epoch deamon
    command: "{{ project_root }}/bin/epoch start"
    when: epoch.stat.exists == True and not ping.stdout == "pong"
    tags: start

  - name: Stoping the epoch deamon
    command: "{{ project_root }}/bin/epoch stop"
    when: epoch.stat.exists == True and ping.stdout == "pong"
    tags: stop
    
  - name: Setting varieble stopped to true
    set_fact:
      stopped: true
    when: epoch.stat.exists == True and ping.stdout == "pong"
    tags: stop

  - name: Restarting the epoch deamon
    command: "{{ project_root }}/bin/epoch restart"
    when: epoch.stat.exists == True and ping.stdout == "pong" and stopped == false
    tags: restart
