---
# Playbook used create mnesia snapshot and upload it to S3

- name: Backup, archive and download Mnesia database
  hosts: "{{ ansible_play_hosts | last }}"
  remote_user: aeternity

  vars:
    snapshot_suffix: snapshot
    snapshot_filename: "mnesia_{{ env }}_v-{{ db_version }}_{{ ansible_ssh_host|default(inventory_hostname) }}_{{ snapshot_suffix }}.tgz"

  tasks:
    - name: Include configuration variables
      include_vars: vars/snapshot.yml

    - name: "Load a variable files for environment: {{ env }}"
      include_vars: "{{ item }}"
      with_first_found:
        - "../vars/aeternity/{{ env }}.yml"
      tags: [config, node_config]

    - name: Stop node
      command: "/bin/true"
      changed_when: true
      notify: "stop aeternity daemon"

    - meta: flush_handlers

    - name: Archive Mnesia Directory (no additional storage)
      archive:
        format: gz
        path: "{{ project_root }}/{{ node_config.chain.db_path }}"
        dest: /tmp/{{ snapshot_filename }}
      when: additional_storage is not defined

    - name: Archive Mnesia Directory (with additional storage)
      archive:
        format: gz
        path: "{{ project_root }}/{{ node_config.chain.db_path }}"
        dest: /tmp/{{ snapshot_filename }}
      when: additional_storage is defined

    - name: Upload backup to S3 bucket
      aws_s3:
        bucket: "{{ snapshots_bucket }}"
        object: "{{ snapshot_filename }}"
        src: /tmp/{{ snapshot_filename }}
        mode: put
        aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        security_token: "{{ lookup('env','AWS_SESSION_TOKEN') }}"

    - name: Upload backup to S3 bucket latest
      aws_s3:
        bucket: "{{ snapshots_bucket }}"
        object: "{{ snapshots_filename_latest }}"
        src: /tmp/{{ snapshot_filename }}
        mode: put
        aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        security_token: "{{ lookup('env','AWS_SESSION_TOKEN') }}"

    - name: Remove Mnesia backups
      file:
        path:  "{{ item }}"
        state: absent
      loop:
        - /tmp/backup
        - /tmp/{{ snapshot_filename }}

    - name: Start node
      command: "/bin/true"
      changed_when: true
      notify: "start aeternity daemon"

  handlers:
  - import_tasks: tasks/handlers.yml
