---
# Playbook used to download mnesia snapshot for env from S3 and restore it to give node

- name: Backup, archive and download Mnesia database
  hosts: all
  remote_user: aeternity

  vars:
    snapshot_path: "{{ snapshots_dir|default('/tmp/snapshots') }}/{{ restore_snapshot_filename|mandatory }}"
    restore_dir: "{{ additional_storage_mountpoint|default(project_root) }}"
    should_restore: true
    force_restore: false

  tasks:
    - name: Include configuration variables
      include_vars: vars/snapshot.yml

    - name: "Load a variable files for environment: {{ env }}"
      include_vars: "{{ item }}"
      with_first_found:
        - "../vars/node_config.yml"
        - "../vars/aeternity/{{ env }}.yml"
      tags: [config, node_config]

    - name: Check if snapshot was restored in {{ restore_dir }}/
      stat:
        path: "{{ restore_dir }}/snapshot_restore"
      register: marker

    - name: Disable restoring (marker exists)
      set_fact:
        should_restore: false
      when:
        - not force_restore
        - marker.stat.exists

    - name: Disable restoring (empty filename)
      set_fact:
        should_restore: false
      when: restore_snapshot_filename == "empty" or restore_snapshot_filename == ""

    - name: Ensure Mnesia snapshots dir exists ({{ snapshots_dir }})
      file:
        path: "{{ snapshots_dir }}"
        state: directory
      when: should_restore

    - name: Download Mnesia snapshot {{ restore_snapshot_filename }}
      aws_s3:
        bucket: "{{ snapshots_bucket }}"
        object: "{{ restore_snapshot_filename }}"
        dest: "{{ snapshot_path }}"
        mode: get
      when: should_restore

    - name: Stop node
      command: "/bin/true"
      changed_when: true
      notify: "stop aeternity daemon"
      when: should_restore

    - meta: flush_handlers

    - name: Restore Mnesia database to {{ restore_dir }}/
      unarchive:
        remote_src: yes
        src: "{{ snapshot_path }}"
        dest: "{{ restore_dir }}/"
      notify: "start aeternity daemon"
      when: should_restore

    - name: Create restore marker
      file:
        path: "{{ restore_dir }}/snapshot_restore"
        state: touch
      when: should_restore

    - name: Delete local Mnesia snapshots ({{ snapshots_dir }})
      file:
        path: "{{ snapshots_dir }}"
        state: absent
      when: should_restore

  handlers:
  - import_tasks: tasks/handlers.yml
