---
- name: Rename epoch user
  hosts: all
  remote_user: master
  become: yes

  vars:
    project_new_user: aeternity
    project_old_user: epoch
    project_old_group: "{{ project_old_user }}"
    project_new_group: "{{ project_new_user }}"
    project_new_home: /home/aeternity
    project_old_home: /home/epoch
    project_root: "{{ project_old_home }}/node/"
    aeternity_bin: "{{ project_root }}/bin/epoch"

  tasks:        
    - name: Check if epoch user exists
      getent:
        database: passwd
        key: "{{ project_old_user }}"
        split: ':'
        fail_key: False
      register: old_user_present

    - name: Check aeternity binary
      stat:
        path: "{{ project_root }}/bin/epoch"
      register: ae_node

    - name: Ping aeternity node
      command: "{{ project_root }}/bin/epoch ping"
      failed_when: no
      register: ping
      when: ae_node.stat.exists == True

    - name: Stop aeternity node
      command: "{{ project_root }}/bin/epoch stop"
      when: (ae_node.stat.exists == True and ping.stdout == "pong") or
            old_user_present.ansible_facts.getent_passwd.epoch != None

    - name: Check new home directory
      stat:
        path: "{{ project_new_home }}"
      register: new_home_present
      
      # Copy modyle does not support recursive directory copying with
      # remote_src
    - name: Move home directory
      command: "mv {{ project_old_home }} {{project_new_home}}"
      when: not new_home_present.stat.exists
      
    - name: Delete epoch user
      user:
        name: "{{ project_old_user }}"
        state: absent
        remove: yes

    - name: Create aeternity user
      user:
        name: "{{ project_new_user }}"
        home: "{{ project_new_home }}"
        create_home: no
        state: present
    - name: Change ownership of new user home directory
      file:
        path: "{{ project_new_home }}"
        owner: "{{ project_new_user }}"
        group: "{{ project_new_user}}"
        recurse: yes

    - name: Create /home/epoch symlink
      file:
        src: "{{ project_new_home }}"
        dest: "{{ project_old_home }}"
        owner: "{{ project_new_user }}"
        group: "{{ project_new_user }}"
        state: link

    - name: Start aeternity node
      command: "{{ project_root }}/bin/epoch start"
      when: old_user_present.ansible_facts.getent_passwd.epoch != None
