---
- name: Reset aeternity test-net
  hosts: all
  remote_user: aeternity

  vars:
    project_root: "{{ ansible_env.HOME }}/node"
    aeternity_bin: "{{ project_root }}/bin/aeternity"

  tasks:
    - name: Aeternity binary exists
      stat:
        path: "{{ aeternity_bin }}"
      register: ae_node
      failed_when: ae_node.stat.exists != True
      changed_when: false
      tags: [daemon]

    - name: Ping aeternity daemon
      command: "{{ aeternity_bin }} ping"
      register: ping
      failed_when: no
      changed_when: false
      tags: [daemon]

    - name: Stop aeternity daemon
      command: "{{ aeternity_bin }} stop"
      when:
        - ae_node.stat.exists
        - ping.stdout == "pong"
      tags: [daemon]

    - name: Stat epoch.yaml
      stat:
        path: "{{ project_root }}/epoch.yaml"
      register: config_file

    - name: Read epoch.yaml contents
      command: "cat {{ project_root }}/epoch.yaml"
      register: cat_output
      when: config_file.stat.exists
      tags: [config]

    - name: Parse YAML configuration
      set_fact:
        node_vars: "{{ cat_output.stdout | from_yaml }}"
      when: config_file.stat.exists
      tags: [config]

    - name: Deleting old blockchain
      file:
        path: "{{ project_root }}/{{ node_vars.chain.db_path }}/"
        state: absent
      when: config_file.stat.exists
      tags: [config]

    - name: Creating new blockchain folder
      file:
        path: "{{ project_root }}/{{ node_vars.chain.db_path }}/"
        state: directory
      when: config_file.stat.exists
      tags: [config]

    - name: Deleting old keys dir
      file:
        path: "{{ project_root }}/{{ node_vars.keys.dir|default('keys') }}/"
        state: absent
      when: config_file.stat.exists
      tags: [config]

    - name: Creating new keys dir
      file:
        path: "{{ project_root }}/{{ node_vars.keys.dir|default('keys') }}/"
        state: directory
      when: config_file.stat.exists
      tags: [config]

    - name: Deleting old log files
      file:
        path: "{{ project_root }}/log/"
        state: absent
      tags: [config]

    - name: Creating new log folder
      file:
        path: "{{ project_root }}/log/"
        state: directory
      tags: [config]

    - name: Start aeternity daemon
      command: "{{ aeternity_bin }} start"
      when: ae_node.stat.exists
      tags: [daemon]

  post_tasks:
    - name: Prepare health checks
      include_tasks: tasks/health_check.yml
      vars:
        node_config: "{{ node_vars }}"
        api_base_uri: http://{{ public_ipv4 }}:{{ node_vars.http.external.port }}/v2
