api_base_uri: http://{{ public_ipv4 }}:{{ epoch_config.http.external.port }}/v2
seed_peers: []

epoch_config:
  sync:
    port: 3015

  http:
    external:
      port: 3013
    internal:
      port: 3113

  keys:
    dir: keys
    peer_password: secret

  chain:
    persist: true
    db_path: "./db{{ db_version|mandatory }}"

  mining:
    beneficiary: "ak_2VoAhMd7tVJrDYM5vPJwFRjueZyirDJumVJNeBWL9j1eNTHsRx"
    cuckoo:
      miner:
        executable: "{{ ('amazon' in ansible_bios_version) | ternary('mean29-avx2', 'mean29-generic')  }}"
        extra_args: "-t {{ ansible_processor_vcpus }}"
        edge_bits: 29

  logging:
    level: warning

  metrics:
      # StatsD server and port
      host: 127.0.0.1
      port: 8125
