datadog_enabled: yes
api_base_uri: http://{{ public_ipv4 }}:{{ epoch_config.http.external.port }}/v2
configure_peers: false
seed_peers:
  - "35.176.170.53"

epoch_config:
  peers:
    - "aenode://pp_2P9y2aA9CzdQRqXQN5e1WdmMaGc4UYNuQ5b9cHNME6wGL71jp6@35.176.170.53:3015"

  sync:
    port: 3015

  http:
    external:
      port: 3013
    internal:
      listen_address: 0.0.0.0
      port: 3113
    debug: true

  keys:
    dir: keys
    peer_password: secret

  chain:
    persist: true
    db_path: "./db{{ db_version|mandatory }}"

  mining:
    autostart: true
    beneficiary: "ak_2VoAhMd7tVJrDYM5vPJwFRjueZyirDJumVJNeBWL9j1eNTHsRx"
    expected_mine_rate: 15000
    cuckoo:
      edge_bits: 15
      miners:
        - executable: mean15-generic
          extra_args: "-t {{ ansible_processor_vcpus }}"

  logging:
    level: warning

  metrics:
      # StatsD server and port
      host: 127.0.0.1
      port: 8125

  fork_management:
    network_id: "ae_fast_integration"
