datadog_enabled: yes
api_base_uri: http://{{ public_ipv4 }}:{{ epoch_config.http.external.port }}/v2
configure_peers: false

epoch_config:
  peers:
    - "aenode://pp_2BCPYYhCKYnLtcNVeyBW1i8D9dZBt2epQXYztFPzibiMB5it6N@18.130.187.37:3015"

  sync:
    port: 3015

  http:
    external:
      port: 3013
    internal:
      listen_address: 0.0.0.0
      port: 3113
    debug: true

  websocket:
    internal:
      listen_address: 0.0.0.0
      port: 3114

  keys:
    dir: keys
    password: secret

  chain:
    persist: true
    db_path: "./db{{ db_version|mandatory }}"

  mining:
    beneficiary: "ak_2VoAhMd7tVJrDYM5vPJwFRjueZyirDJumVJNeBWL9j1eNTHsRx"
    expected_mine_rate: 15000
    cuckoo:
      miner:
        executable: "{{ ('amazon' in ansible_bios_version) | ternary('mean16s-avx2', 'mean16s-generic')  }}"
        extra_args: "-t {{ ansible_processor_vcpus }}"
        node_bits: 16

  logging:
    level: warning

  metrics:
      # StatsD server and port
      host: 127.0.0.1
      port: 8125
