datadog_enabled: yes
api_base_uri: http://{{ public_ipv4 }}:{{ epoch_config.http.external.port }}/v2
genesis_accounts:
  "ak_UAzhn9rAQg568v6Hwt3w2HPaQb9X9Nw6JbLmnv7trhmGmWGGp": 100000000001
configure_peers: false

epoch_config:
  peers:
    - "aenode://pp_PVNHha6SBXQBdh8XsiAma2auMjyDodZAY7BGjd8xir6g6JPBM@31.13.249.71:3015"
    - "aenode://pp_Hj8oJx1oESu6QNEVLc1K63jezfj61B4SmuyhF5RWfJACaZgry@31.13.249.72:3015"
    - "aenode://pp_2Jx7N2qDUqu3ZNfd831Byiq4WofebBsSRHNTD79Tcsr9VTTt54@31.13.249.73:3015"

  sync:
    port: 3015

  http:
    external:
      port: 3013
    internal:
      port: 3113

  keys:
    dir: keys
    password: secret

  chain:
    persist: true
    db_path: "./db{{ db_version|mandatory }}"

  mining:
    beneficiary: "ak_2VoAhMd7tVJrDYM5vPJwFRjueZyirDJumVJNeBWL9j1eNTHsRx"
    cuckoo:
      miner:
        executable: "{{ ('amazon' in ansible_bios_version) | ternary('mean30s-avx2', 'mean30s-generic')  }}"
        extra_args: "-t {{ ansible_processor_vcpus }}"
        node_bits: 30

  logging:
    level: debug

  metrics:
      # StatsD server and port
      host: 127.0.0.1
      port: 8125
