datadog_enabled: yes
api_base_uri: http://{{ public_ipv4 }}:{{ epoch_config.http.external.port }}/v2
genesis_accounts:
  "ak_UAzhn9rAQg568v6Hwt3w2HPaQb9X9Nw6JbLmnv7trhmGmWGGp": "100000000001"
configure_peers: false
seed_peers:
  - "18.130.142.111"

epoch_config:
  peers:
    - "aenode://pp_2SmwgNAp8zgHqNfCJEu5xLp7rN281ocnomAeEuJ5UPnkavroDs@18.130.142.111:3015"

  sync:
    port: 3015

  http:
    external:
      port: 3013
    internal:
      port: 3113

  keys:
    dir: keys
    peer_password: secret

  chain:
    persist: true
    db_path: "./db{{ db_version|mandatory }}"

  mining:
    beneficiary: "ak_2VoAhMd7tVJrDYM5vPJwFRjueZyirDJumVJNeBWL9j1eNTHsRx"
    cuckoo:
      miner:
        executable: "{{ ('amazon' in ansible_bios_version) | ternary('mean30s-avx2', 'mean30s-generic')  }}"
        extra_args: "-t {{ ansible_processor_vcpus }}"
        node_bits: 30

  logging:
    level: debug

  metrics:
      # StatsD server and port
      host: 127.0.0.1
      port: 8125
