api_base_uri: http://{{ public_ipv4 }}:{{ epoch_config.http.external.port }}/v2
genesis_accounts:
  "ak_UAzhn9rAQg568v6Hwt3w2HPaQb9X9Nw6JbLmnv7trhmGmWGGp": 100000000001
package: https://s3.eu-central-1.amazonaws.com/aeternity-epoch-builds/epoch-latest-ubuntu-x86_64.tar.gz
health_check: no
configure_peers: true
seed_peers: []

epoch_config:
  sync:
    port: 3015

  http:
    external:
      port: 3013
    internal:
      port: 3113

  keys:
    dir: keys
    peer_password: secret

  chain:
    persist: true
    db_path: "./db"

  mining:
    autostart: true
    beneficiary: "ak_2VoAhMd7tVJrDYM5vPJwFRjueZyirDJumVJNeBWL9j1eNTHsRx"
    cuckoo:
      miner:
        executable: mean29-avx2
        extra_args: "-t {{ ansible_processor_vcpus }}"
        edge_bits: 29

  logging:
    level: debug

  metrics:
      # StatsD server and port
      host: 127.0.0.1
      port: 8125
