api_base_uri: http://{{ public_ipv4 }}:{{ epoch_config.http.external.port }}/v2
configure_peers: false
seed_peers:
  - "52.10.46.160"
  - "18.195.109.60"
  - "13.250.162.250"
  - "18.130.148.7"

epoch_config:
  sync:
    port: 3015

  http:
    external:
      port: 3013
    internal:
      port: 3113

  keys:
    dir: keys
    peer_password: secret

  chain:
    persist: true
    db_path: "./db{{ db_version|mandatory }}"

  mining:
    beneficiary: "ak_tjnw1KcmnwfqXvhtGa9GRjanbHM3t6PmEWEWtNMM3ouvNKRu5"
    cuckoo:
      miner:
        executable: mean29-avx2
        extra_args: "-t 1"
        edge_bits: 29

  logging:
    level: warning

  metrics:
      # StatsD server and port
      host: 127.0.0.1
      port: 8125
